framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            assets/app: app
            assets/orange-pizza: orange-pizza
            assets/brave-elephant: brave-elephant
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
